# Generated by Django 5.0.3 on 2024-03-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('idPlayer', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=93)),
                ('playerHeight', models.FloatField()),
                ('playerWeight', models.FloatField()),
                ('positionPlayer', models.CharField(max_length=93)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('idTeam', models.AutoField(primary_key=True, serialize=False)),
                ('nameTeam', models.CharField(max_length=93)),
                ('sedeTeam', models.CharField(max_length=93)),
            ],
        ),
    ]
