# Generated by Django 5.0.3 on 2024-03-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_idteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='equipos/default.png', null=True, upload_to='equipos'),
        ),
    ]
